### PR TITLE
add modules for rke1 control-plane + rancher setup

### PR DESCRIPTION
**Pull request by git-ival**
These changes add 4 new modules to the control-plane root module:

- aws-infra: a generalized infrastructure module specific to AWS (not reliant on a specific K8s distribution
  - Intentended to be built upon/added to in order to support any/all K8s distributions we may want to test against going forward
- rke1: a module for setting up an rke cluster using the `rke` terraform provider
  - Currently assumes an AWS infra, but is intended to be updated to be cloud provider-agnostic
- generate-kube-config: self-explanatory, a module for generating a local kube-config file
- install-common: a module for installing cert-manager and rancher using the `helm` terraform provider
  - This may become the default method of installing the Rancher Server for all K8s distributions in the future
 
 Moved root control-plane module providers into providers.tf and data into data.tf.
 
 README.md files have been added for each added module and the control-plane README.md has been updated as well.
 
 Additionally, the `rancher2.admin` terraform provider is being used to install rancher-monitoring for rke1 K8s clusters. Rather than using the `helm` provider, this may become the default method of installing Rancher charts via terraform for all K8s distributions in the future.

### CODE REVIEW

**Comment by git-ival** [comment]
Rebased to remove unused/misc files

**Comment by git-ival** [comment]
Rebased to remove unused/misc files and add aws-k3s changes to account for root control-plane module changes

**Comment by git-ival** [comment]
Added additional sleep post cert-manager install to avoid https://github.com/rancher/rancher/issues/36108

**Comment by git-ival** [comment]
Rebase: 
* Added additional sleep post cert-manager install to avoid https://github.com/rancher/rancher/issues/36108
* Updated node naming format

**Review by bmdepesa — APPROVED** [review]

**Pull request merged**
